env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
   "no-console": "off",
   'import/extensions': ['error', 'ignorePackages', {
      js: 'off',
      mjs: 'off',
      jsx: 'off',
    }],
    "import/no-named-as-default": 0,
    "import/no-named-as-default-member": 0

}
